name: iotconnect-gg-nucleus
version: '2.16.1'
summary: Greengrass v2 Nucleus configurator for Ubuntu Core
description: A Python application to configure and install Greengrass v2 (compatible with AWS IoT Greengrass)

base: core22
confinement: strict
grade: stable

environment:
  PATH: $SNAP/usr/bin:$SNAP/bin:$SNAP/docker/bin:$PATH
  PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3.10/dist-packages:$SNAP/lib/python3.10/site-packages:$PYTHONPATH
  JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-$SNAP_ARCH

platforms:
  arm64:
  amd64:

layout:
  /etc/ssl/certs/java:
    bind: $SNAP/etc/ssl/certs/java

plugs:
  docker-executables:
    interface: content
    content: docker-executables
    target: $SNAP/docker
    default-provider: docker

slots:
  shared-files:
    interface: content
    content: shared-files
    source:
      read:
        - $SNAP/shared

apps:
  configure:
    command: bin/python3 $SNAP/bin/iot-greengrass-setup.py
    plugs:
      - network
      - network-bind
      - home
      - system-observe
      - mount-observe
      - hardware-observe
      - process-control
      - docker-executables
      - docker
      - camera
    slots:
      - shared-files

  greengrass-daemon:
    command: bin/greengrass-wrapper.sh
    daemon: simple
    restart-condition: always
    restart-delay: 10s
    plugs:
      - network
      - network-bind
      - home
      - system-observe
      - mount-observe
      - hardware-observe
      - process-control
      - log-observe
      - docker-executables
      - docker
      - camera
    slots:
      - shared-files

parts:
  iot-greengrass-app:
    plugin: python
    source: .
    python-requirements:
      - requirements.txt
    stage-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-11-jre-headless
      - python3-pip
    build-packages:
      - wget
      - ca-certificates-java
      - openjdk-11-jre-headless
    override-build: |
      # Run default Python plugin build first
      craftctl default

      # Create directory and download Greengrass installer
      mkdir -p $CRAFT_PART_INSTALL/opt/greengrass
      wget -O $CRAFT_PART_INSTALL/opt/greengrass/greengrass-nucleus.zip \
        https://d2s8p88vqu9w66.cloudfront.net/releases/greengrass-2.16.1.zip

      # Ensure Python script is executable and in correct location
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp local-scripts/iot-greengrass-setup.py $CRAFT_PART_INSTALL/bin/
      chmod +x $CRAFT_PART_INSTALL/bin/iot-greengrass-setup.py

      cp local-scripts/greengrass-wrapper.sh $CRAFT_PART_INSTALL/bin/
      chmod +x $CRAFT_PART_INSTALL/bin/greengrass-wrapper.sh

      ARCH="$(dpkg --print-architecture)"

      mkdir -p $CRAFT_PART_INSTALL/etc/ssl/certs/java
      mkdir -p $CRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-${ARCH}/lib/security
      touch $CRAFT_PART_INSTALL/etc/ssl/certs/blacklisted.certs

      rm -f $CRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-${ARCH}/lib/security/blacklisted.certs
      touch $CRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-${ARCH}/lib/security/blacklisted.certs

      # The OpenJDK package provides cacerts as an external symlink; generate and copy a real file.
      update-ca-certificates -f || true
      if command -v update-ca-certificates-java >/dev/null 2>&1; then
        update-ca-certificates-java -f || true
      fi

      CACERTS_FILE="$CRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-${ARCH}/lib/security/cacerts"
      rm -f "$CACERTS_FILE"
      if [ -f "/etc/ssl/certs/java/cacerts" ]; then
        cp "/etc/ssl/certs/java/cacerts" "$CACERTS_FILE"
      else
        echo "ERROR: Unable to locate /etc/ssl/certs/java/cacerts after update."
        exit 1
      fi

    organize:
      shared/: shared/
